package com.acuevas.vetstucom.model;

import com.acuevas.vetstucom.exceptions.ApplicationException;
import com.acuevas.vetstucom.exceptions.ApplicationException.AppErrors;

/**
 * Stores the profiles allowed to {@link Usuarios#tipoUsuario}, used to check
 * which type the user is.
 * 
 * @author Alex
 *
 */
public enum UserPerfil {
	AUXILIAR, VETERINARIO, ADMIN;

	public UserPerfil getUserType(Usuarios user) throws ApplicationException {
		switch (user.getTipoUsuario()) {
		case 1:
			return UserPerfil.AUXILIAR;
		case 2:
			return UserPerfil.VETERINARIO;
		case 3:
			return UserPerfil.ADMIN;

		default:
			throw new ApplicationException(AppErrors.TYPE_DOESNT_EXIST);
		}
	}
}

// TODO DECIDED TO PUT THE ENUM OUTSIDE USUARIOS'S CLASS IN ORDER TO NOT MODIFY THE POJO GENERATED BY HIBERNATE
// TODO DOCUMENTATE: IF YOU WANT TO MODIFY TIPO USUARIO'S NUMBER YOU'LL ONLY HAVE TO CHANGE THIS CLASS AND THE REST OF THE APPLICATION WILL WORK