package com.acuevas.vetstucom.exceptions;

/**
 * Exceptions generated by the user, not critical to the application.
 * 
 * @author Alex
 *
 */
public class UserException extends Exception {
	private static final long serialVersionUID = -3436387005310241193L;

	public enum UserErrors {
		WRONG_CREDENTIALS("Username or password incorrect."), OPTION_NOT_VALID("Option not valid."),
		USER_ALREADY_EXISTS("Username already in use");

		private String message;

		private UserErrors(String message) {
			this.message = message;
		}

	}

	public UserException(UserErrors error) {
		super(error.message);
	}

}
